### ISSUE TITLE
Issue with certificate when deployed on Azure

### ISSUE THREAD

**Issue by Milan4e** [MewsSystems/fiscalization-czechia#44]
Hi, 

The implementation locally works fine, however when deployed on an Azure webjob I get the following error in logs: 

The code throwing exception is:

```
var certificate = new Certificate(password: "pw_here", data: File.ReadAllBytes(fullPath));

```
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Security.Cryptography.CryptographicException: Invalid provider type specified.

at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
at Mews.Eet.Dto.Certificate..ctor(String password, Byte[] data)
```
Locally and on the webjob I am running .NET framework 4.7.1

Anyone with a similar issue?

Thanks!

**Comment by KaliCZ** [comment]
@Milan4e Hey, are you using version 2.0.1? Can you please try version 2.0.0 and let us know if that works? We have made some changes to this part in order to migrate to .net standard. We will take a look at the possible causes.

**Comment by Milan4e** [comment]
@KaliCZ thanks for your reply. I installed version 1.1.9 (2.0.0 is not in NuGet Package Manager), but it did not work. Same error message on Azure, however it works fine locally.

**Comment by mrnustik** [comment]
@Milan4e 
Have you tried setting the useMachineKeyStore flag to true? 
It was added previously in a #29 to support running on Azure.

**Comment by BreakTheWheel** [comment]
@mrnustik that worked! Thanks for the suggestion!

Just to note, the flag is not present on the latest version, I still had to use the 1.1.9 version of the package. 

Thanks!

**Comment by Milan4e** [comment]
@mrnustik that worked! Thanks a lot for your suggestion!

Just to note, the flag is not present on the latest version of the package so I still have to use version 1.1.9, which is fine, but I am not sure why it was removed.
thanks again!

**Comment by marektresnak** [comment]
Hi, we didn't think the option was actually used by anyone, but we should have checked the history more thoroughly.

We have now published a new version which brings the flag back: https://www.nuget.org/packages/Mews.Eet/2.1.0
