### ISSUE TITLE
SendRevenueAsync crashing on Microsoft.Net.Sdk.Web . 

### ISSUE THREAD

**Issue by gandus** [MewsSystems/fiscalization-czechia#55]
When I run same snippet on Microsoft.Net.Sdk and Microsoft.Net.Sdk.Web, on  Microsoft.Net.Sdk my snippet executes successfully. But on Microsoft.Net.Sdk.Web SendRevenueAsync crashes with exception "CryptographicException: Could not create hash algorithm object" 
whole stack trace: 
   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()
   at Mews.Eet.Communication.SoapSigner.SignMessage(XmlDocument xmlDoc)
   at Mews.Eet.Communication.SoapMessage.GetSignedXmlDocument(Certificate certificate, SignAlgorithm signAlgorithm)
   at Mews.Eet.Communication.SoapClient.<SendAsync>d__22`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Mews.Eet.Communication.EetSoapClient.<SendRevenueAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Mews.Eet.EetClient.<SendRevenueAsync>d__13.MoveNext()
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at EETTest.Program.Main(String[] args) in C:\Users\Gandu\source\repos\EETTest\EETTest\Program.cs:line 36
 
 My code snippet:
 `        
        static void Main(string[] args)
        {
            var rawData = File.ReadAllBytes("Certs/7536BC7C96627378436CB3C6A4DD6294E355B820");
            var certificate = new Certificate("eet", rawData);

            var record = new RevenueRecord(
                identification: new Identification(
                    taxPayerIdentifier: new TaxIdentifier("CZ08221499"),
                    registryIdentifier: new RegistryIdentifier("01"),
                    premisesIdentifier: new PremisesIdentifier(1),
                    certificate: certificate                ),
                revenue: new Revenue(
                    gross: new CurrencyValue(1234.00m)
                ),
                billNumber: new BillNumber("2016-321")
            );

            var securityCode = record.SecurityCode; // BKP
            var signature = record.Signature; // PKP

            var client = new EetClient(certificate, EetEnvironment.Playground);
            var response = client.SendRevenueAsync(record).Result;
            if (response.IsSuccess)
            {
                var fiscalCode = response.Success.FiscalCode;
            }
        }
        `

**Comment by marektresnak** [comment]
Hi @gandus, I have to say we never encountered this issue specifically. But with some of other libraries, we have encountered other issues related to cryptography when trying to move to the .NET core platform. The solution was usually to search for some alternative, which worked properly on all platforms.

Have you had any success solving this one? If you managed to find a solution that would work on all platforms, feel free to open a PR :)

**Comment by KaliCZ** [comment]
Closed due to inactivity. If still happening, pls reopen in the [new repo](https://github.com/MewsSystems/fiscalizations).
